# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9.2.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
  custom:
    deploy:
      - step:
          name: Deploy to Prod
          deployment: production
          script:
             - export FOLDER=`date +%s`
             - ssh $USER@$HOST "mkdir ${FOLDER}"
             - scp -r [!.]* $USER@$HOST:~/${FOLDER}/.
             - ssh $USER@$HOST "ln -sfn ~/${FOLDER} ~/pkmn_app"
             - ssh $USER@$HOST "cd ~/pkmn_app; npm install; env PORT=\"${PORT}\" TOKEN=\"${TOKEN}\" REDIS_URL=\"${REDIS_URL}\" sh start.sh"
             